In [2]:
import pandas as pd
import numpy as np

In [6]:
employee_data = {
    "Employee_ID":[200,20,186,175,33,74,191,220,219],

    "Name":[
         "shree","Harshad","Tarang","Gargii",
    "Pranjal_D","PJ","Sakshii",
    "Anuj","Revatii"

    ],

    "Department":[
        "Professor",
        "Assistant Professor",
        "Lab Staff",
        "Admin Staff",
        "Clerk",
        "Professor","Admin Staff",
        "Clerk",
        "Professor"
    ],

    "Basic_Salary":[100000,150,50000,80000,90000,150000,8999,3456,12345]
    
}

df = pd.DataFrame(employee_data)

df

   Employee_ID       Name           Department  Basic_Salary
0          200      shree            Professor        100000
1           20    Harshad  Assistant Professor           150
2          186     Tarang            Lab Staff         50000
3          175     Gargii          Admin Staff         80000
4           33  Pranjal_D                Clerk         90000
5           74         PJ            Professor        150000
6          191    Sakshii          Admin Staff          8999
7          220       Anuj                Clerk          3456
8          219    Revatii            Professor         12345

In [7]:
df["HRA"] = df["Basic_Salary"] * 0.20

df["Bonus"] = np.where(
    df["Department"].isin(
        ["Professor","Assistant Professor"]
    ),
    df["Basic_Salary"]*0.10,
    df["Basic_Salary"]*0.05
)

df["Tax"] = df["Basic_Salary"]*0.08

df["Final_Salary"] = (
    df["Basic_Salary"]
    + df["HRA"]
    + df["Bonus"]
    - df["Tax"]
)

df

,Employee_ID,Name,Department,Basic_Salary,HRA,Bonus,Tax,Final_Salary
0,200,shree,Professor,100000,20000.0,10000.00,8000.00,122000.00
1,20,Harshad,Assistant Professor,150,30.0,15.00,12.00,183.00
2,186,Tarang,Lab Staff,50000,10000.0,2500.00,4000.00,58500.00
3,175,Gargii,Admin Staff,80000,16000.0,4000.00,6400.00,93600.00
4,33,Pranjal_D,Clerk,90000,18000.0,4500.00,7200.00,105300.00
5,74,PJ,Professor,150000,30000.0,15000.00,12000.00,183000.00
6,191,Sakshii,Admin Staff,8999,1799.8,449.95,719.92,10528.83
7,220,Anuj,Clerk,3456,691.2,172.80,276.48,4043.52
8,219,Revatii,Professor,12345,2469.0,1234.50,987.60,15060.90

In [8]:


print("\nAverage Salary:")
print(df["Final_Salary"].mean())

print("\nHighest Salary:")
print(df["Final_Salary"].max())

print("\nLowest Salary:")
print(df["Final_Salary"].min())

Average Salary:
65801.80555555556

Highest Salary:
183000.0

Lowest Salary:
183.0

In [9]:
department_report = df.groupby(
    "Department"
)["Final_Salary"].mean()

department_report

Department
Admin Staff             52064.415000
Assistant Professor       183.000000
Clerk                   54671.760000
Lab Staff               58500.000000
Professor              106686.966667
Name: Final_Salary, dtype: float64

In [10]:
top_employee = df.loc[
    df["Final_Salary"].idxmax()
]

print(top_employee)

Employee_ID            74
Name                   PJ
Department      Professor
Basic_Salary       150000
HRA               30000.0
Bonus             15000.0
Tax               12000.0
Final_Salary     183000.0
Name: 5, dtype: object

In [11]:
np.random.seed(42)

names = [
     "shree","Harshad","Tarang","Gargii",
    "Pranjal","Anjali","Sakshii",
    "Anuj","Revatii"
]

departments = [
    "Professor",
    "Assistant Professor",
    "Lab Staff",
    "Admin Staff"
]

salary_df = pd.DataFrame({

    "Name":np.random.choice(
        names,10
    ),

    "Department":np.random.choice(
        departments,10
    ),

    "Basic_Salary":np.random.randint(
        30000,
        100000,
        10
    )
})

salary_df

      Name           Department  Basic_Salary
0  Sakshii          Admin Staff         97969
1   Gargii          Admin Staff         35311
2     Anuj            Lab Staff         83707
3  Pranjal  Assistant Professor         58693
4  Sakshii            Professor         55658
5   Tarang  Assistant Professor         48431
6  Sakshii          Admin Staff         32747
7     Anuj          Admin Staff         89150
8  Pranjal  Assistant Professor         95725
9   Gargii  Assistant Professor         65773

In [12]:
salary_df["HRA"] = salary_df["Basic_Salary"]*0.20

salary_df["Bonus"] = np.where(
    salary_df["Department"].isin(
        ["Professor","Assistant Professor"]
    ),
    salary_df["Basic_Salary"]*0.10,
    salary_df["Basic_Salary"]*0.05
)

salary_df["Tax"] = salary_df["Basic_Salary"]*0.08

salary_df["Net_Salary"] = (

    salary_df["Basic_Salary"]
    + salary_df["HRA"]
    + salary_df["Bonus"]
    - salary_df["Tax"]
)

salary_df

,Name,Department,Basic_Salary,HRA,Bonus,Tax,Net_Salary
0,Sakshii,Admin Staff,97969,19593.8,4898.45,7837.52,114623.73
1,Gargii,Admin Staff,35311,7062.2,1765.55,2824.88,41313.87
2,Anuj,Lab Staff,83707,16741.4,4185.35,6696.56,97937.19
3,Pranjal,Assistant Professor,58693,11738.6,5869.30,4695.44,71605.46
4,Sakshii,Professor,55658,11131.6,5565.80,4452.64,67902.76
5,Tarang,Assistant Professor,48431,9686.2,4843.10,3874.48,59085.82
6,Sakshii,Admin Staff,32747,6549.4,1637.35,2619.76,38313.99
7,Anuj,Admin Staff,89150,17830.0,4457.50,7132.00,104305.50
8,Pranjal,Assistant Professor,95725,19145.0,9572.50,7658.00,116784.50
9,Gargii,Assistant Professor,65773,13154.6,6577.30,5261.84,80243.06

In [13]:
top_employee = df.loc[
    df["Final_Salary"].idxmax()
]

print(top_employee)

Employee_ID            74
Name                   PJ
Department      Professor
Basic_Salary       150000
HRA               30000.0
Bonus             15000.0
Tax               12000.0
Final_Salary     183000.0
Name: 5, dtype: object